#config:
#  name: gateway开发服务
#server:
#  port: 8000
#
#spring:
#  application:
#    name: liu-gateway-service
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.11.251:8848
#        username: nacos
#        password: nacos
#        namespace: 33e90e1d-4a78-414c-8dea-28893135dd5a
#        group: DEFAULT_GROUP
#        weight: 1
#      server-addr: 192.168.11.251:8848
#    gateway:
#      routes: #数组形式
#        # 用户服务
#        - id: liu-user-service  #商品服务 路由唯一标识
#          uri: lb://liu-user-service #从nocas进行转发
#          order: 1 #优先级，数字越小优先级越高
#          predicates: #断言 配置哪个路径才转发，前端访问路径统一加上XXX-server，网关判断转发对应的服务，如果是回调业务记得修改
#            - Path=/user-server/**
#          filters: #过滤器，请求在传递过程中通过过滤器修改
#            - StripPrefix=1  #去掉第一层前缀，转发给后续的路径
#        # 订单服务
#        - id: liu-order-service  #商品服务 路由唯一标识
#          uri: lb://liu-order-service #从nocas进行转发
#          order: 1 #优先级，数字越小优先级越高
#          predicates: #断言 配置哪个路径才转发，前端访问路径统一加上XXX-server，网关判断转发对应的服务，如果是回调业务记得修改
#            - Path=/order-server/**
#          filters: #过滤器，请求在传递过程中通过过滤器修改
#            - StripPrefix=1  #去掉第一层前缀，转发给后续的路径
#
#      #开启网关拉取nacos的服务
#      discovery:
#        locator:
#          enabled: true
#
##设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
#logging:
#  level:
#    root: INFO
#    com.alibaba.nacos.client.config.impl: WARN